# codemagic.yaml

# ────────────────────── CODESIGNING SETUP ──────────────────────
code_signing:
  automatic:
    apple_team: P4XSL5RZ3H
    bundle_identifier: com.example.legaryanKare

# ────────────────────── WORKFLOWS ────────────────────────────
workflows:

  # ───────────── 1️⃣ Simulator smoke-test & QA ─────────────
  test-ios-simulator:
    name: Test iOS (Simulator & QA)
    environment:
      flutter: stable

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Run unit tests
        script: flutter test --machine

      - name: Run integration tests
        script: flutter test --machine integration_test

      - name: Build for iOS simulator
        script: flutter build ios --simulator --no-codesign

    artifact_paths:
      - build/ios/iphonesimulator/Runner.app

  # ───────────── 2️⃣ iOS Release (signed) ─────────────
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    vars:
      APP_STORE_CONNECT_PRIVATE_KEY: Encrypted
      APP_STORE_CONNECT_KEY_ID:      Encrypted
      APP_STORE_CONNECT_ISSUER_ID:   Encrypted

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Bump pubspec build number
        script: |
          echo "Incrementing build number…"
          CURRENT=$(grep -E '^version:' pubspec.yaml | sed -E 's/.*\+([0-9]+)/\1/')
          NEXT=$((CURRENT+1))
          sed -i.bak -E "s/\+[0-9]+$/+$NEXT/" pubspec.yaml
          echo "New version line: $(grep -E '^version:' pubspec.yaml)"

      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build signed IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - pubspec.yaml

    publishing:
      app_store_connect:
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
        key_id:    $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # submit_to_app_store: true
