# ───────────── Code Signing (Automatic) ─────────────
code_signing:
  automatic:
    apple_team: P4XSL5RZ3H
    bundle_identifier: com.example.legaryanKare

# ───────────── Workflows ─────────────
workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build signed IPA (automatic signing)
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
