workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build signed IPA with automatic code signing
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: Harikar   # This matches your Codemagic integration name
        submit_to_app_store: true
        publish_on_failure: true

    code_signing:
      automatic:
        apple_team: P4XSL5RZ3H
        bundle_identifier: com.example.legaryanKare
