workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: CocoaPods setup and install
        script: |
          sudo gem install cocoapods -n /usr/local/bin
          cd ios
          echo "platform :ios, '12.0'" > Podfile
          pod cache clean --all
          pod install --repo-update
          cd ..

      - name: Build iOS .ipa
        script: flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
