name: Harikar
description: "A new Flutter project for looking for work."
publish_to: "none"

version: 1.0.4+9

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.2.1
  shared_preferences: ^2.2.2
  mysql1: ^0.20.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  blur: ^3.0.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.7.0
  photo_view: ^0.14.0
  dropdown_search: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/fonts/
  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
