platform :ios, '12.0'
use_frameworks!
use_modular_headers!

target 'Runner' do
  # Flutter’s own iOS pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Runner'
      target.build_configurations.each do |config|
        # force Xcode to embed Swift stdlibs
        config.build_settings['EMBEDDED_CONTENT_CONTAINS_SWIFT_CODE']     = 'YES'
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES']    = 'YES'
      end
    end
  end
end
